<a href="https://colab.research.google.com/github/Rohitsingh24-cloud/chat-with-yt-video/blob/main/nnmoduleinpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
import torch.nn as nn

In [4]:
#we have to inherit our class fron nn module so that we use its functionality
class model(nn.Module):
  def __init__(self,num_features):
    #it is used to invoke parent class which is nn
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()
  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

In [5]:
#create dataset

In [6]:
features=torch.rand(10,5)

In [7]:
Model=model(5)

In [8]:
Model(features)

tensor([[0.5248],
        [0.4961],
        [0.5322],
        [0.5027],
        [0.4605],
        [0.5201],
        [0.4637],
        [0.5204],
        [0.4554],
        [0.4992]], grad_fn=<SigmoidBackward0>)

In [9]:
Model.linear.weight

Parameter containing:
tensor([[0.1254, 0.1931, 0.2959, 0.0235, 0.0588]], requires_grad=True)

In [11]:
Model.linear.bias

Parameter containing:
tensor([-0.3502], requires_grad=True)

In [12]:
!pip install torchinfo

In [13]:
from torchinfo import summary

In [14]:
summary(Model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [16]:
class model2(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1=nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()
  def forward(self,features):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)
    return out

In [17]:
#create dataset

In [18]:
features=torch.rand(100,3)
model=model2(3)


In [19]:
model(features)

tensor([[0.6327],
        [0.6529],
        [0.5924],
        [0.6561],
        [0.6361],
        [0.6353],
        [0.6155],
        [0.6160],
        [0.6031],
        [0.6429],
        [0.6145],
        [0.5977],
        [0.6474],
        [0.6071],
        [0.6309],
        [0.6251],
        [0.6429],
        [0.6745],
        [0.5910],
        [0.6729],
        [0.6172],
        [0.6201],
        [0.6104],
        [0.6406],
        [0.6297],
        [0.6249],
        [0.6479],
        [0.5983],
        [0.6322],
        [0.6058],
        [0.6083],
        [0.6699],
        [0.6507],
        [0.6034],
        [0.6435],
        [0.6532],
        [0.6682],
        [0.6007],
        [0.6471],
        [0.6572],
        [0.6100],
        [0.6178],
        [0.6332],
        [0.6559],
        [0.6565],
        [0.6050],
        [0.6248],
        [0.6050],
        [0.6535],
        [0.5943],
        [0.6269],
        [0.6674],
        [0.6378],
        [0.6581],
        [0.6574],
        [0

In [24]:
model.linear1.weight

Parameter containing:
tensor([[ 0.0350,  0.0097,  0.5131],
        [-0.3323,  0.3039,  0.1798],
        [-0.0842,  0.3805,  0.3047]], requires_grad=True)

In [25]:
model.linear1.bias

Parameter containing:
tensor([-0.1010,  0.1643,  0.4558], requires_grad=True)

In [26]:
model.linear2.weight

Parameter containing:
tensor([[ 0.5442,  0.4241, -0.1713]], requires_grad=True)

In [27]:
summary(model,input_size=(100,3))

Layer (type:depth-idx)                   Output Shape              Param #
model2                                   [100, 1]                  --
├─Linear: 1-1                            [100, 3]                  12
├─ReLU: 1-2                              [100, 3]                  --
├─Linear: 1-3                            [100, 1]                  4
├─Sigmoid: 1-4                           [100, 1]                  --
Total params: 16
Trainable params: 16
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#sequential container

In [28]:
#when we writing forward function in model it seem to be a hectitic to pass one data to another so we use sequential

In [29]:
class model2(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
      nn.Linear(num_features,3),
      nn.ReLU(),
      nn.Linear(3,1),
      nn.Sigmoid()
    )
  def forward(self,features):
    out=self.network(features)
    return out

In [30]:
#changes in previous code


In [31]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [32]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [33]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [34]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [35]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [36]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [37]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [45]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out







In [46]:
learning_rate = 0.1
epochs = 25

In [51]:
loss_function=nn.BCELoss()

In [58]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])
model=model.double()
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
#model.parameter is an iterator that give all paramter in  model

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1).double())
  #zero gradient
  optimizer.zero_grad()
  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()


  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.5564169084829564
Epoch: 2, Loss: 0.4585549981526056
Epoch: 3, Loss: 0.398790691014805
Epoch: 4, Loss: 0.35819290163434736
Epoch: 5, Loss: 0.32850192390634525
Epoch: 6, Loss: 0.3056354433766928
Epoch: 7, Loss: 0.28734914871523537
Epoch: 8, Loss: 0.27230377470349587
Epoch: 9, Loss: 0.25964767952748113
Epoch: 10, Loss: 0.24881135130382517
Epoch: 11, Loss: 0.2393981477915489
Epoch: 12, Loss: 0.23112244186936684
Epoch: 13, Loss: 0.22377273793094346
Epoch: 14, Loss: 0.2171886979686249
Epoch: 15, Loss: 0.21124629119718205
Epoch: 16, Loss: 0.20584788413977967
Epoch: 17, Loss: 0.20091544249456636
Epoch: 18, Loss: 0.19638575381822979
Epoch: 19, Loss: 0.19220699827965484
Epoch: 20, Loss: 0.1883362403269299
Epoch: 21, Loss: 0.1847375629078909
Epoch: 22, Loss: 0.1813806585875279
Epoch: 23, Loss: 0.1782397511256316
Epoch: 24, Loss: 0.17529275977237288
Epoch: 25, Loss: 0.172520644344416


In [59]:
model.linear.weight

Parameter containing:
tensor([[ 0.2688,  0.2855,  0.3592,  0.2565, -0.0080,  0.1319,  0.2639,  0.3217,
         -0.0406, -0.0395,  0.1506, -0.1338,  0.2401,  0.1656,  0.0755,  0.1242,
         -0.0237,  0.1750, -0.0821, -0.1532,  0.3161,  0.0812,  0.0574,  0.3344,
          0.0566,  0.2247,  0.0561,  0.2597,  0.0977,  0.1777]],
       dtype=torch.float64, requires_grad=True)

In [60]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5784856677055359
